### ISSUE TITLE
pos-print: make receipts equivalent

### ISSUE THREAD

**Issue by gadjevb** [clouway/pos-print#45]
Non-fiscal and fiscal receipt should be made to be with equivalent templates:

![dsc_0837](https://cloud.githubusercontent.com/assets/19385077/25231185/960c5880-25df-11e7-9489-22c564e29cf9.JPG)

**Comment by mgenov** [comment]
Partially fixed by removing hard-coded lines from both in #47

**Comment by mgenov** [comment]
@mlesikov do we have to do something else in this direction ?
