### ISSUE TITLE
pos-print: endpoints for printing of receipts

### ISSUE THREAD

**Issue by mgenov** [clouway/pos-print#9]
Client Apps should be able to print receipts using the provided endpoints: 

Print Receipt

**POST /v1/posprint**
```json
{
  "sourceIp": "89.100.10.5",
  "operatorId": "??",
  "receipt": {"receiptId": "123", "currency": "BGN", "prefixLines": ["Customer: John"], "suffixLines": [], "amount": 20.00, "receiptItems": [{"name": "HSI 80/40", "quantity": 1.0, "price": 0.10}]}}
```

**Comment by FeNoMeNa** [comment]
What do you think about ```POST /v1/devices/:id/print``` ?

**Comment by mgenov** [comment]
The client apps will have to query list of devices for a given ip and then to use it. It will add a one more roundtrip. 

It will be easier if device is queried internally by the application instead.
